name: fz.facemash
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  cached_network_image: ^2.2.0+1
  in_app_purchase: ^0.3.4+3
  provider: ^4.3.2+1
  connectivity: ^0.4.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_rename_app: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/facemash.png"

flutter_rename_app:
  application_name: Facemash
  dart_package_name: fz.facemash
  application_id: com.fz.facemash
  bundle_id: com.fz.facemash
  android_package_name: com.fz.facemash

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/facemash.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

